### ISSUE TITLE
Error when packet size is greater than 2000

### ISSUE THREAD

**Issue by joecoder1021** [ffalcinelli/pydivert#21]
I tried testing with ping of 2000 bytes and received the following error:

  File "...\Programs\Python\Python35\lib\site-packages\pydivert\windivert.py", line 214, in send
    byref(send_len))
  File "...Programs\Python\Python35\lib\site-packages\pydivert\windivert_dll\__init__.py", line 55, in wrapper

**Comment by ffalcinelli** [comment]
This depends on the MTU. In my network I have a MTU at 1500, so I get your error when I reach a greater packet'size:  

```
ping 10.0.2.2 -l 1473
```

Packet len is 1501 indeed

```
'ipv4': {'dst_addr': '10.0.2.2',
          'packet_len': 1501,
          'raw': <memory at 0x0000029C1333B288>,
          'src_addr': '10.0.2.15'},
```

So I think you need to fragment the packet before reinjecting.

**Comment by joecoder1021** [comment]
I am not sure how to fragment the packets.
I will do some research on this, but if you have any information on how to do this please let me know, thanks.

Sent from my iPad

On Feb 6, 2017, at 6:58 AM, Fabio Falcinelli <notifications@github.com<mailto:notifications@github.com>> wrote:


This depends on the MTU. In my network I have a MTU at 1500, so I get your error when I reach a greater packet'size:

ping 10.0.2.2 -l 1473


Packet len is 1501 indeed

'ipv4': {'dst_addr': '10.0.2.2',
          'packet_len': 1501,
          'raw': <memory at 0x0000029C1333B288>,
          'src_addr': '10.0.2.15'},


So I think you need to fragment the packet before reinjecting.

**Comment by ffalcinelli** [comment]
Well right now pydivert has no easy API to change IP headers deeply, but you can do everything on the raw packet bytes (You may want to take a look at [jdivert](https://github.com/ffalcinelli/jdivert)).

You can read here for an example: http://www.tech-faq.com/packet-fragmentation.html

**Comment by ffalcinelli** [comment]
With commit 726d92890bff337ae28ee563992f8e94b967f119 there are properties to set IPv4 header fields (unless options which I'll implement one day soon :no_mouth: )

You may give them a try. 

I found a lot of bugs in jdivert implementation in this way :scream:
