### ISSUE TITLE
Support more header fields

### ISSUE THREAD

**Issue by ffalcinelli** [ffalcinelli/pydivert#22]
Some applications may want better flexibility upon packet modification like setting DF (Don't Fragment) flag or fragment offset (see #21 )

**Comment by mhils** [comment]
Yes, that sounds useful. :+1:
The natural place for this to go is pydivert/packet/ip.py 🙂

**Comment by ffalcinelli** [comment]
Closed with a0546225c757d54adcd9df981271d57d47356d83 😉
