### ISSUE TITLE
It can't capture some packets from a PC used as a gateway

### ISSUE THREAD

**Issue by adgarciaar** [ffalcinelli/pydivert#43]
I'm trying to use a PC as a gateway that filters the communication between two other PCs, Unfortunately, pydivert can't capture packets that travel between the two machines to communicate, but it can capture packets that travel from one of the two machines to the PC gateway. I know the limitation because I'm using Wireshark at the same time. This on Windows 10.

Thanks for your help.

Cheers,

Adrian.

**Comment by mhils** [comment]
This works for us in mitmproxy. Are you using `pydivert.Layer.NETWORK_FORWARD`?

**Comment by adgarciaar** [comment]
yes, I try but it didn't work, maybe I am stablishing Layer.NETWORK_FORWARD incorrectly, can you provide me the code line to do that? In the meantime I'll try again

**Comment by adgarciaar** [comment]
Thank you very much @mhils, it's working
