### ISSUE TITLE
Now my computer has connected many vpn,i set up it and make it no global proxy ,now i need to make every vpn has Local Proxy by setting them,now i cannot to Surf the Internet by listen to miniport（vpn）by proxy .

### ISSUE THREAD

**Issue by 54huige** [ffalcinelli/pydivert#44]
VPN transformation local agent.
Local proxy to VPN
Can it be achieved? on windows.
Now my computer has connected many vpn,i set up it and make it no global proxy ,now i need to make every vpn has Local Proxy by setting them,now i cannot to Surf the Internet by listen to miniport（vpn）by proxy .

**Comment by mhils** [comment]
This doesn't seem to be an applicatiopn-specific question rather than a pydivert issue. It's probably something you can build with PyDivert, but it's not easy and we can't help you with it.

**Comment by mhils** [comment]
This seems to be an application-specific question rather than a pydivert issue. This can probably be implemented with PyDivert, but it's not easy and we can't help you. Sorry!
