### ISSUE TITLE
How to use EXCEPT?

### ISSUE THREAD

**Issue by romkazor** [ffalcinelli/pydivert#50]
Hello. I try to use:

not (tcp.DstPort=80 or tcp.DstPort=443)
or
!(tcp.DstPort=80 or tcp.DstPort=443)

But it's working as (tcp.DstPort=80 or tcp.DstPort=443)

What's wrong? Thanks.

**Comment by majibow** [comment]
As a work around you can change it to:
tcp.DstPort!=80 and tcp.DstPort!=443
